### ISSUE TITLE
Validator modification for RSA key in Sealva vds validation tool

### ISSUE THREAD

**Issue by alam156** [tsenger/vdstools#10] opened 2024-11-25 04:31 UTC
Hi tsenger, I have modified the code for RSA key instead of EC key. I have modified signer and verifier class and generated qr code accordingly. Now, while validating qr code with sealva app, it throws signature is invalid. I am thinking that Sealva app is using EC key's logic in their end. Do you have any source code repo for sealva app? and is it shareable?

**Comment by tsenger** [comment] 2024-11-25 08:28
Hi, yes Sealva uses the vdstools for parsing and verification. And no, der source for Sealva isn't public available.
VDS according to ISO9304 Part 13 does not contain a certificate but only a reference to it. This means that the certificate must be provided elsewhere in order to verify the signature. 
But as I said, the specification only provides for ECDSA signatures for reasons of space. An RSA 2048 signature alone already has 256 bytes. With ECDSA on a 256-bit curve, a signature consists of only 32 bytes. As the space available for the 2D barcode of digital seals is usually quite limited, attempts are made to save as many bytes as possible. In my view, RSA therefore makes no sense for VDS.
But if you have a different use case, you can of course also use RSA in your projects.

**Comment by alam156** [comment] 2024-11-26 08:13
Hi tsenger, thanks for your response. As Sealva is not public yet, i am trying to develop an app to verify the data and DATA_MATRIX.
For this purpose, I am creating a QRCode of type DATA_MATRIX from encodedBytes i am getting from DigitalSeal.
Now in my android app i am getting DATA_MATRIX contents in result.getContents().
I am trying to create digitalseal in android app from byte array. 
I am using following line of code for conversion
`
DigitalSeal digitalSealToVerify = DigitalSeal.fromByteArray(result.getContents().getBytes(StandardCharsets.ISO_8859_1));
`
But it throws error while parsing and giving NullPointerException.
Is there any other way around you can suggest?

**Comment by tsenger** [comment] 2024-11-26 08:49
VDS seals are Base256 encoded. So to build a DATAMATRIX from the digitalSeal.getEncoded() you have first to encode them to Base256.

```
DataMatrixWriter dmw = new DataMatrixWriter();
BitMatrix bitMatrix = dmw.encode(
    DataEncoder.encodeBase256(digitalSeal.getEncoded()), 
    BarcodeFormat.DATA_MATRIX, 450, 450); 
```

What data type returns your result.getContents()? If it returns a (Base256-)String you should use DigitalSeal.fromRawString(rawString).

**Comment by alam156** [comment] 2024-11-27 04:28
Hi, tsenger, I am using exactly same code snippet above. I debugged the code using my QRCode.
I found out that, everything is working fine after calling `parseVdsSeal(DataParser.decodeBase256(rawString));`
`vdsHeader, vdsMessage` fields are populated and `vdsSignature` is null. But when calling `DigitalSeal(vdsHeader, vdsMessage, vdsSignature);` it throws null. I fully omitted SignatureReference from the vds library because of javax dependency.

**Comment by alam156** [comment] 2024-11-27 09:47
After a lot of debugging, i found out that `DigitalSeal digitalSealToVerify = DigitalSeal.fromRawString(result.getContents());` throws some runtime exception.

**Comment by tsenger** [comment] 2024-11-27 15:36
Depends on the content ;-)
But seriously, without seeing your code and what data you are using exactly, I can't say if it's a bug in the vdstools. Maybe you just fork the vdstools into your account and make your changes there.
I will not implement RSA in this repo, but feel free to do this in your fork. 
I'm closing this issue now, as it is not an issue with the current implementation, but rather seems to be due to your modifications.

**Closed as not planned by tsenger** 2024-11-27 15:36 UTC

**Comment by alam156** [comment] 2024-11-28 03:24
Hi tsenger, Thanks. 
I have forked your git repo to my repo. the repo is here
https://github.com/alam156/vdstools.git
In main class, i have tried to generate a QRCode of type DATA_MATRIX and verify the signature.
In order to verify signature i have used the encodedBytes. But the encodedBytes should come from converting DATA_MATRIX to bytearray. I did it in my android app and then it throws exception while creating digital seal from rawString.
I have modified signer and verifier class and added main class in this project.
My android client for vds verification is given below
https://github.com/alam156/vdsVerifier.git
I have added my generated QRCode using rsa private key.
![test](https://github.com/user-attachments/assets/2edce310-cb3d-4fa8-b871-d92010461120)

**Comment by tsenger** [comment] 2024-11-28 09:31
Can't see why it isn't working. I scanned your datamatrix with the Sealva-App and it parses and shows the data. Of course the Signature is shown as invalid because the app only support ECDSA-Signature.

**Comment by alam156** [comment] 2024-11-28 10:15
I think the conversion from DATA_MATRIX to byte array is problematic. In my android app it throws null pointer exception while creating digital seal from rawString. I think, It needs a small change in sealva app.

**Comment by alam156** [comment] 2024-11-29 05:59
I created a QRCode of type DATA_MATRIX using EC private key and EC certificate. But, Sealva app still says the signature is invalid. I have use EC Curve of type prime256v1 while creating key
![test_ec](https://github.com/user-attachments/assets/755c352d-1c44-4af9-b71e-27c5d613e87d)

**Comment by tsenger** [comment] 2024-11-29 06:45
Yes thats correct. You can't create a valid signature which match the public key in Certificate DETS32 without the matching private key. I assume you have created your own keypair to sign the seal. Of course Sealva does not know this keypair. But since you have specified DETS32 as the signer reference in the header, Sealva tries to check the signature with this certificate, which of course fails because it is the wrong certificate.

**Comment by alam156** [comment] 2024-11-29 07:16
Then how can i check from my side the verification is working perfectly for EC key and certificate from my side? can i create DETS32 type certificate using command line tool of openssl?

**Comment by alam156** [comment] 2024-11-29 21:28
Hi tsenger, I have tried with EC key and certificate in my android application. It still throws NullPointerException in below line
```
DigitalSeal digitalSealToVerify = DigitalSeal.fromRawString(result.getContents());
```
So, in my opinion, it's not rsa or ec key related problem, it's in contents. The content is not in right format to create digital seal.

**Comment by alam156** [comment] 2024-11-30 07:40
Hi tsenger, thanks for your regular cooperation. 

can you please provide p12 file for one of UTTS025B,DETS0232,DETS024F,DETS0227 (DETS32 preferred) which also have private key.(not only .cer file)?

Then I can check from my side and start finding the issue why ec key based p12 parsing throws null pointer exception.

How can i create these type of certificates using openssl?

**Comment by alam156** [comment] 2024-12-02 04:51
Hi, tsenger, I have successfully generated visible digital seal using this repo and sealva app also verifies the seal successfully.
The issue is with my android app, may be the null pointer exception is thrown because of some formatting issue of raw String.
If possible, could you please share the source code of sealva app temporarily?
If it's not possible could you share QR code scanning part of sealva app?

**Comment by tsenger** [comment] 2024-12-02 16:08
Nice, that's now possible to verify. 
I had an look an your repo for the verification app. It could be that the Exceptions ist caused by the missing SealsCoding.json in the resources folder. The vdstools contain this file if you use the package from maven. But if you just copy the sources you have also to put the SealsCoding.json to the resource folder. Seems you maybe missed that?
The Sealva app calls the zxing barcode scanner the same way as you did in your repo. So that shouldn't be a problem. 

Ah, and if you want to generate certificates may have a look on XCA (https://hohnstaedt.de/xca/). It's a nice little open source CA software to generate and manage certificates.

**Comment by alam156** [comment] 2024-12-08 10:06
Thanks tsenger for your suggestions.
 now, it throws the exception "java.lang.IllegalArgumentException: Certificate should contain EC public key!"
I am using dets0232.cer and dets32 certificate from bks file. still it says above error. What i have got from code is that the public key is not an instance of ECPublickey. could you please tell me how can i resolve this?

**Comment by alam156** [comment] 2024-12-09 04:07
Hi tsenger, my app also able to verify the signature. Now i want to add my own EC certificate while signing. Do i need to add the certificate in bks file in android client? How can the client know my certificate information in android client side?
Another query is do you have any testcase scenario which focused on COVID-19 certificate verification?

**Comment by tsenger** [comment] 2024-12-09 07:35
Please have a look a the specs. It's all in there:
https://www.icao.int/publications/Documents/9303_p13_cons_en.pdf

VDS-NC are not supported. But this is the spec:
https://www.icao.int/Security/FAL/TRIP/PublishingImages/Pages/Publications/Visible%20Digital%20Seal%20for%20non-constrained%20environments%20%28VDS-NC%29.pdf

**Comment by alam156** [comment] 2024-12-11 03:23
nice! i am trying to add a new vds type to support covid 19 certificate which is of type vds-nc. is it possible with the existing code.
I am concerned that vds-nc have json text as vds message.

**Comment by alam156** [comment] 2024-12-12 07:44
Thanks a lot tsenger, we are able to restructure the code to support rsa key pair. We have successfully implemented our use case based solution using this repository.
